name: PostgreSQL service example
on: push

jobs:

  container-job:

    runs-on: ubuntu-latest

    container: node:14


    services:

      postgres:

        image: postgres

        env:
          POSTGRES_PASSWORD: 12345
          POSTGRES_USER: mm
          POSTGRES_DB: good-car
          POSTGRES_PORT: 5432

        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:

      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm ci

      - name: Connect to PostgreSQL

        run: npm run testDB 

        env: 
          DB_URL_test: postgres://mm:12345@postgres:5432/good-car

      - name: testing Routes

        run: npm run testRoutes

        env: 
          DB_URL_test: postgres://mm:12345@postgres:5432/good-car